services:
  gene:
    depends_on:
      - db
    environment:
      PRETTY_URLS: "1"
      LANG: "en-US"
      BASE_URL: "https://gene.example.com"
      DB_TYPE: "pgsql"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "webtrees"
      DB_PASS: ""
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
      WT_USER: ""
      WT_NAME: ""
      WT_PASS: ""
      WT_EMAIL: ""
      PUID: "1000"
      PGID: "1000"
    image: ghcr.io/nathanvaughn/webtrees:latest
      #ports:
      #- 7000:80
      # - 443:443
    restart: unless-stopped
    volumes:
      # - ~/certs:/certs/
      - app_data:/var/www/webtrees/data/


  db:
    environment:
      POSTGRES_DB: "webtrees"
      POSTGRES_USER: "webtrees"
      POSTGRES_PASSWORD: ""
    image: docker.io/library/postgres:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
